const { JWT_LOCAL_SECRET = 'JWT_SECRET' } = process.env;
const { bdlocaladdress = 'mongodb://localhost:27017/mestodb' } = process.env;
module.exports = {
  JWT_LOCAL_SECRET,
  bdlocaladdress,
};

const dguSdmoModbusVocabulary = [
  'PhL1N_V',
  'PhL2N_V',
  'PhL3N_V',
  'PhL1L2_V',
  'PhL2L3_V',
  'PhL1L3_V',
  'CurL1_A',
  'CurL2_A',
  'CurL3_A',
  'Power_kW',
  'Power_kVA',
  'PowerFactor',
  'PowL1_kW',
  'PowL2_kW',
  'PowL3_kW',
  'PowL1_kVa',
  'PowL2_kVa',
  'PowL3_kVa',
  'PowerFactorL1',
  'PowerFactorL2',
  'PowerFactorL3',
  'LoadCharacter',
  'RPMEngine',
  'GenFreq',
  'prp',
  'Ubat',
  'Bin',
  'Bout',
  'OilPressure',
  'CTemp',
  'Fuel',
  'UnitSystem',
  'DplusChargingAlt',
  'ActEn1',
  'ActEn2',
  'Mtimer',
  'StartCounter',
  'GensetSN1',
  'GensetSN2',
  'SWversion',
  'SWpatch',
];
